version: 2.1

jobs:
  build:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo build

  unit_test:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo unit test

  integration_test:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo integration test

  deploy:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo deploy

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - unit_test: 
          requires: 
            - build
      - integration_test:
          requires: 
           - unit_test
      - deploy:
          requires:
            - integration_test
